name: Build URL lists & RAW sitemap
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate URL lists & RAW sitemap
        run: |
          set -euo pipefail
          OWNER="Agdistys"
          REPO="Conversations"
          PAGES_BASE="https://${OWNER}.github.io/${REPO}"
          RAW_BASE="https://raw.githubusercontent.com/${OWNER}/${REPO}/main"

          # 👉 Ajoute d'autres dossiers ici si besoin
          DIRS=("Reconnaissance")

          for DIR in "${DIRS[@]}"; do
            if [ -d "$DIR" ]; then
              LIST="$(mktemp)"
              find "$DIR" -type f | sort > "$LIST"

              # fichiers .txt avec toutes les URLs
              awk -v b="$PAGES_BASE" '{print b"/"$0}' "$LIST" > "${DIR//\//-}-urls-pages.txt"
              awk -v b="$RAW_BASE"   '{print b"/"$0}' "$LIST" > "${DIR//\//-}-urls-raw.txt"

              # sitemap XML (version RAW)
              {
                echo '<?xml version="1.0" encoding="UTF-8"?>'
                echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
                while IFS= read -r f; do
                  printf '  <url><loc>%s/%s</loc></url>\n' "$RAW_BASE" "$f"
                done < "$LIST"
                echo '</urlset>'
              } > "sitemap-${DIR//\//-}-raw.xml"
            fi
          done

      - name: Commit artifacts
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *-urls-raw.txt *-urls-pages.txt sitemap-*-raw.xml || true
          git commit -m "ci: update raw/pages URL lists & RAW sitemap" || echo "nothing to commit"
          git push || true
