name: Build URL lists & sitemap
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate URL lists for Reconnaissance
        run: |
          set -e
          BASE_PAGES="https://agdistys.github.io/Conversations"
          BASE_RAW="https://raw.githubusercontent.com/Agdistys/Conversations/main"
          # listes .txt
          find Reconnaissance -type f | sort > /tmp/recon-files.txt
          awk -v b="$BASE_PAGES" '{print b"/"$0}' /tmp/recon-files.txt > reconnaissance-urls-pages.txt
          awk -v b="$BASE_RAW"   '{print b"/"$0}' /tmp/recon-files.txt > reconnaissance-urls-raw.txt
          # sitemap XML simple
          {
            echo '<?xml version="1.0" encoding="UTF-8"?>'
            echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
            while IFS= read -r f; do
              printf '  <url><loc>%s/%s</loc></url>\n' "$BASE_PAGES" "$f"
            done < /tmp/recon-files.txt
            echo '</urlset>'
          } > sitemap-reconnaissance.xml

      - name: Commit URL lists
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add reconnaissance-urls-raw.txt reconnaissance-urls-pages.txt sitemap-reconnaissance.xml
          git commit -m "ci: generate raw/pages URL lists & sitemap for Reconnaissance" || echo "nothing to commit"
          git push
